# Generated by Django 5.0.7 on 2024-07-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cell',
            new_name='minesweeper_cells',
        ),
    ]
