# Generated by Django 5.0.7 on 2024-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_rename_cell_minesweeper_cells'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweeper_active',
            name='amount_of_moves',
            field=models.IntegerField(default=0),
        ),
    ]
