# Generated by Django 5.0.7 on 2024-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0003_minesweeper_active_amount_of_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweeper_cells',
            name='adjacent_mines',
            field=models.IntegerField(default=0),
        ),
    ]
