# Generated by Django 5.0.7 on 2024-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_tictactoe_archive_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe_archive',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
